source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
platform :ios, '7.0'
pod 'SDWebImage', '~>3.7'
pod 'SVProgressHUD'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'CocoaLumberjack'
